name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node + npm cache
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Rust crate + target cache
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install frontend dependencies
        run: npm ci

      - name: Build and Release Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: StashyJD ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false

# while pushing tag and push
# package.json - "version": "0.1.0" -> "version": "0.1.1"
# tauri.conf.json - "version": "0.1.0" -> "version": "0.1.1"
# git add .
# git commit -m "Bump version to 0.1.16"
# git tag v0.1.16
# git push
# git push origin v0.1.16
