name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install

      - name: Decode signing key
        shell: bash
        run: |
          echo "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}" | base64 --decode > private.key

      - name: Build and Release Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY_PATH: private.key
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: StashyJD ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false

# while pushing tag and push
# package.json - "version": "0.1.0" -> "version": "0.1.1"
# tauri.conf.json - "version": "0.1.0" -> "version": "0.1.1"
# git add .
# git commit -m "Bump version to 0.1.1"
# git tag v0.1.1
# git push
# git push origin v0.1.1
